name: Lab02 Reuse and Artifacts
run-name: Lab02 - ${{ github.actor }} is calling Composite Actions ðŸš€
permissions: read-all
on:
  workflow_dispatch:
jobs:
  run-template:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
      # Run the template with parameters
      - id: dotnet-build
        uses: ./.github/workflows/build-dotnet-app
        with:
          folder-path: "apps/uptodate-app"
      # Publish output folder as an artifact
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ steps.dotnet-build.outputs.output-directory-path }}
