name: Lab01 Variables and Secrets
run-name: Lab01 - ${{ github.actor }} is testing variables and secrets ðŸš€
permissions: read-all
on:
  workflow_dispatch:
jobs:
  demo:
    runs-on: ubuntu-latest
    # Define a global environment variable for this job
    env:
      MY_VARIABLE: "Hello from the environment variable!"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Echo Variable and Secret
        env:
          # For this to work, you need to create a repository secret on GitHub.com
          # 1. Go to your repository on GitHub.com
          # 2.  Navigate to Settings > Secrets and variables > Actions
          # 3. Click "New repository secret"
          # 4. Name: DEMO_SECRET
          # 5. Value: your-secret-value

          # Assign the repository secret to an environment variable for this step
          DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
        run: |
          echo "Environment Variable: $MY_VARIABLE"
          echo "Secret Value: $DEMO_SECRET"
          echo "Note how the secret value is not printed to the log"
